# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=40, verbose_name='姓名')),
                ('h_age', models.IntegerField(default=30, verbose_name='年龄')),
                ('h_gender', models.BooleanField(default=False, verbose_name='性别')),
                ('h_birthday', models.DateTimeField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '英雄',
                'verbose_name_plural': '英雄',
            },
        ),
        migrations.CreateModel(
            name='Hero_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=40, verbose_name='书名')),
                ('b_info', models.CharField(max_length=4000, verbose_name='简介')),
                ('b_date', models.DateTimeField(verbose_name='出版时间')),
                ('b_number', models.IntegerField(verbose_name='出版量')),
            ],
            options={
                'verbose_name': '发行书籍',
                'verbose_name_plural': '发行书籍',
            },
        ),
    ]
