# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='h_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Hero_Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='h_birthday',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出生日期'),
        ),
    ]
