# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20180711_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='h_book',
        ),
        migrations.AddField(
            model_name='hero_book',
            name='b_hero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Hero'),
            preserve_default=False,
        ),
    ]
