# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=40, verbose_name='班级')),
                ('g_num', models.IntegerField(default=20, verbose_name='人数')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=40, verbose_name='姓名')),
                ('s_gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('s_age', models.IntegerField(default=20, verbose_name='年龄')),
                ('s_graden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Graden')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
            },
        ),
    ]
