# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='python1805', max_length=40, verbose_name='班级名称')),
                ('g_number', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='s_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.Grade'),
        ),
    ]
